### ISSUE TITLE
Aimbot is not existent lol

### ISSUE THREAD

**Issue by ghost** [papstuc/counterstrike2#2]

**Comment by papstuc** [comment]
~~Could you maybe describe the failing behavior? Does the aimbot not aim at enemies?~~

Edit: Coding problem at my end. I made some huge mistakes while coding retarded at 4am.
The signature to get the controller would be rescanned at each run and the aimbot would obtain the pawn_handle of the current controller even if it's a nullptr making it crash and lag huge.

I pushed several fixes to the main branch. Could you pull it and confirm its working for you too?

[video of the expected behavior](https://streamable.com/oaugbk)

**Comment by ghost** [comment]
Thanks for working on a fix for it. I understand that coding mistakes can happen, especially when working at odd hours lol, I appreciate your prompt action in addressing the problem and pushing the fixes to the main branch. I will definitely pull the latest changes and mess around some some more. 

if you're taking suggestions at this point in time I would love to see a visibility check added for the aimbot and some selectable hitboxes it would also be nice to see bhop implemented. 👍

**Comment by papstuc** [comment]
Hitboxes are being implemented right now. The visibility check is a bit trickier to do as it requires to ray trace and this functionality I have yet to reverse and understand.

Note that I cannot work 24/7 on this project even if I would like to due to having to study for exams.
