### ISSUE TITLE
Does not work, crashes

### ISSUE THREAD

**Issue by CMAULTOP** [papstuc/counterstrike2#4]

**Comment by a55uka** [comment]
DLL injection, since cs2 released publicly, seems to be detected by the game unless -insecure is used when launching the game

**Comment by CMAULTOP** [comment]
Like now it is impossible to inject through `process hacker`? It just used to be done by throwing the dll into the windows folder

**Comment by a55uka** [comment]
Yep, injecting DLLs via process hacker seems to only work with insecure, this seems like this is the case for many injection methods as well. CS2 ac seems to detect the injects

**Comment by papstuc** [comment]
Of course it crashes, the project was made during the early beta phase of Counter-Strike 2 and hasn't been updated since then.
You are free to update it to the newest version and make a pull request.

Injecting a DLL with ProcessHacker hasn't been working in CS:GO for years now since they are blocking the injection, but you can still manual map it.

**Comment by CMAULTOP** [comment]
And which injector should I choose?

**Comment by a55uka** [comment]
A simple manual map will work, however the sigs will have to be updated
